//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBootstrapSite1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppBootstrapSite1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AcademicCalender {
            get {
                return ResourceManager.GetString("AcademicCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AcademicCalenderHeading {
            get {
                return ResourceManager.GetString("AcademicCalenderHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two periodical exams will be held annually: (a) First temporal (b) Second temp.
        ///Weekly and other examinations will be held in &apos;Jami&apos;ah&apos; prescribed rules.
        ///There should be 80% presence in the examination.
        ///Can not attend the examination without the entrance test.
        ///Must be present at the examination for 10 minutes before the start of the test.
        ///Any disciplinary action may be taken including the expulsion for irregularities in the examination.
        ///Conducting mischief in the examination would be considered inadeq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AcademicExam {
            get {
                return ResourceManager.GetString("AcademicExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Guidelines.
        /// </summary>
        public static string AcademicExamHeading {
            get {
                return ResourceManager.GetString("AcademicExamHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission.
        /// </summary>
        public static string AdmissionHeading {
            get {
                return ResourceManager.GetString("AdmissionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdmissionSubtitle {
            get {
                return ResourceManager.GetString("AdmissionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (a) Al Jamiah As Salafiah, Narayanganj:
        ///
        ///(i) Boys section: Total land area for boys section is 450 decimals. In the boys section, the educational program is going on from class 1 to class XI. With the mercy of Allah, a five-storied residential building has been established, with 10 rooms having 18/20 feet below the floor. A tin-shaded building with 4 rooms is situated on the south-west side of this building. There is a generator room, an employee&apos;s residential room and two other storerooms. There is a six [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AtAGlanceJamiyahDetails {
            get {
                return ResourceManager.GetString("AtAGlanceJamiyahDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Jamiah As Salafiah At a Glance.
        /// </summary>
        public static string AtAGlanceJamiyahHeading {
            get {
                return ResourceManager.GetString("AtAGlanceJamiyahHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (a) Al Jamiah As Salafiah, Narayanganj:
        ///President: Mr. Shaykh Abdur Razzak Bin Yusuf.
        ///Vice President: Mr. Shahadat Hossain.
        ///Secretary: Janab Marfat Ali.
        ///Convener: Mr. Salah Uddin.
        ///Founding Member: Mr. Abdus Subhan.
        ///Member: Mr. Nayan.
        ///Member: Mr. Hashem Ali.
        ///(b) Al Jamiah As Salafiah, Rajshahi:
        ///President: Mr. Shaykh Abdur Razzaq bin Yusuf
        ///Vice President: Mr. Imran Ali Molla
        ///Secretary: Ziaur Rahman
        ///Treasury: Mr. Obaidullah
        ///Member: Mr. Yamin Ali Molla
        ///Member: Mr. Golam Mortaza
        ///Member: Mr. Abdul  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BoardOfDirectorDetails {
            get {
                return ResourceManager.GetString("BoardOfDirectorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board of Directors:.
        /// </summary>
        public static string BoardOfDirectorHeading {
            get {
                return ResourceManager.GetString("BoardOfDirectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Chairman {
            get {
                return ResourceManager.GetString("Chairman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChairmanHeading {
            get {
                return ResourceManager.GetString("ChairmanHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ClassRoutine {
            get {
                return ResourceManager.GetString("ClassRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ClassRoutineHeading {
            get {
                return ResourceManager.GetString("ClassRoutineHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CoursesDetails {
            get {
                return ResourceManager.GetString("CoursesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string CoursesDetailsHeading {
            get {
                return ResourceManager.GetString("CoursesDetailsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DailyMeal {
            get {
                return ResourceManager.GetString("DailyMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food list.
        /// </summary>
        public static string DailyMealHeading {
            get {
                return ResourceManager.GetString("DailyMealHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom Clothing: Jami&apos;ah&apos;s Punjabi and Pajamas determined. White hat of yarn
        ///Residential Hall Clothing: Any type of lungi and loosely dresses. Huff or flower shovel ginger. Ashlon is prohibited by any dress..
        /// </summary>
        public static string DressCode {
            get {
                return ResourceManager.GetString("DressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students&apos; clothing.
        /// </summary>
        public static string DressCodeHeading {
            get {
                return ResourceManager.GetString("DressCodeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jami&apos;ah&apos;s education course is divided into 4 levels
        ///  Ibtaydayi or primary = 5 years
        ///  Mutwasasitah or secondary = 5 years
        ///  Chanubia or Higher Secondary = 2 years
        ///  Fazilat (dora) or higher = 3 years.
        /// </summary>
        public static string GalleryDetails {
            get {
                return ResourceManager.GetString("GalleryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string GalleryHeading {
            get {
                return ResourceManager.GetString("GalleryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (a) The history of Al Jamiah As Salafiah, Narayanganj: A Furkania Madrasha (Religious School) was established in 1954 by the effort of the famous physician Doctor Abdus Subhan in association of some Islam loving brothers because there were no institutions for learning the Holy Quran in that area of Birhatabo, Rupganj, Narayanganj. Afterwards the institution’s name was changed as  Amdia Krishak-Sramik Hafizia Madrasha. Due to financial crisis, the institution was closed in 1996. After five long years, in 200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HistoryOfInstitutionDetails {
            get {
                return ResourceManager.GetString("HistoryOfInstitutionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Of Institution Heading.
        /// </summary>
        public static string HistoryOfInstitutionHeading {
            get {
                return ResourceManager.GetString("HistoryOfInstitutionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying in the light of its own syllabus determined in the form of advanced syllabus of local and foreign institutions.
        ///Directed by a handful of skilled, experienced, hardworking and dedicated teachers from various universities and universities of the country and abroad.
        ///If you are resident then always supervised by the teachers.
        ///A daily meal of 3 &apos;daily&apos; food as well as vegetarian and vegetarian food.
        ///Along with attaining full proficiency in Arabic and English language, there is also a chance to gain  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JamiyahLifeDetails {
            get {
                return ResourceManager.GetString("JamiyahLifeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madrasa Characteristics.
        /// </summary>
        public static string JamiyahLifeHeading {
            get {
                return ResourceManager.GetString("JamiyahLifeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying in the light of its own syllabus determined in the form of advanced syllabus of local and foreign institutions.
        ///Directed by a handful of skilled, experienced, hardworking and dedicated teachers from various universities and universities of the country and abroad.
        ///If you are resident then always supervised by the teachers.
        ///A daily meal of 3 &apos;daily&apos; food as well as vegetarian and vegetarian food.
        ///Along with attaining full proficiency in Arabic and English language, there is also a chance to gain  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MadrashaCharacteristics {
            get {
                return ResourceManager.GetString("MadrashaCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madrasa Characteristics.
        /// </summary>
        public static string MadrashaCharacteristicsHeading {
            get {
                return ResourceManager.GetString("MadrashaCharacteristicsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MonthlyExpenses {
            get {
                return ResourceManager.GetString("MonthlyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MonthlyExpensesHeading {
            get {
                return ResourceManager.GetString("MonthlyExpensesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoticeDetails {
            get {
                return ResourceManager.GetString("NoticeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string NoticeHeading {
            get {
                return ResourceManager.GetString("NoticeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoticeSubtitle {
            get {
                return ResourceManager.GetString("NoticeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Shaykh Abdur Razzaq bin Yusuf&apos; &apos;To spread the teachings of Quran and Saheeh hadeeth on the soil of Bangladesh on 24th August 2013, in the Rupganj, Narayanganj, and in February 2016, in Rajshahi,&apos; Al-Jami&apos;ah as-Salafiyah &apos;, two simultaneous standard Islamic teachings The organization was established. Falilahil Hamd.
        /// </summary>
        public static string OurMadrasha {
            get {
                return ResourceManager.GetString("OurMadrasha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OurMadrashaDetails {
            get {
                return ResourceManager.GetString("OurMadrashaDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Madrasha.
        /// </summary>
        public static string OurMadrashaHeading {
            get {
                return ResourceManager.GetString("OurMadrashaHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our madrassa.
        /// </summary>
        public static string OurMadrashaModelHeading {
            get {
                return ResourceManager.GetString("OurMadrashaModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Shaykh Abdur Razzaq bin Yusuf&apos; &apos;To spread the teachings of Quran and Saheeh hadeeth on the soil of Bangladesh on 24th August 2013, in the Rupganj, Narayanganj, and in February 2016, in Rajshahi,&apos; Al-Jami&apos;ah as-Salafiyah &apos;, two simultaneous standard Islamic  &apos;Shaykh Abdur Razzaq bin Yusuf&apos; &apos;To spread the teachings of Quran and Saheeh hadeeth on the soil of Bangladesh on 24th August 2013, in the Rupganj, Narayanganj, and in February 2016, in Rajshahi,&apos; Al-Jami&apos;ah as-Salafiyah &apos;, two simultaneous standard Isl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OurMadrashaSubtitle {
            get {
                return ResourceManager.GetString("OurMadrashaSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within a year of the establishment of Jami&apos;ah Salafiyah, with the help of the great God, we have been able to construct residential buildings of three-storeyed students, which have 10 rooms with 18/20 feet below the floor. And 4 rooms of 15/20 feet brick walls have been built for the students. Falilahil Hamd
        ///At present, there are 118 students, 10 teachers, four employees and 31 students, 5 teachers and 1 staff in the department of students in this organization.
        ///In the first year of his establishment, Jami [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OurSuccess {
            get {
                return ResourceManager.GetString("OurSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our success.
        /// </summary>
        public static string OurSuccessHeading {
            get {
                return ResourceManager.GetString("OurSuccessHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents should keep track of the child&apos;s education and pay monthly fees payable in due time.
        ///Parents should inform any complaint to the office along with the complaint and their good advice will be accepted in the interest of the organization&apos;s development.
        ///Parents will not be able to meet the child or contact the phone without the scheduled time.
        ///Parents can not stay in the students room.
        ///Encourage the students to comply with the rules of the organization.
        ///After the quarterly and temporary examination [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ParentalResponsiblity {
            get {
                return ResourceManager.GetString("ParentalResponsiblity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents are responsible for the responsibility.
        /// </summary>
        public static string ParentalResponsiblityHeading {
            get {
                return ResourceManager.GetString("ParentalResponsiblityHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born: Sheikh Abdur Razzak Bin Yusuf was born in a religious family of Hajirtala village under Maunga box under Devinagar upazila of Chapainawabganj district of northern Bangladesh.
        ///
        ///Studying: After studying Maktab in the field of education, he read from Nawabganj Nawabganj Madrasa, one of the books of Hadith, Mishkat Sharif. Then he went to India hoping for higher education and finished Daura Hadith from Darul Ulum Maunathwangan in Uttar Pradesh. He ended the two-day tradition of Dora. Then he returned to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string PrincipalHeading {
            get {
                return ResourceManager.GetString("PrincipalHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultHeading {
            get {
                return ResourceManager.GetString("ResultHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudentLists {
            get {
                return ResourceManager.GetString("StudentLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students List.
        /// </summary>
        public static string StudentListsHeading {
            get {
                return ResourceManager.GetString("StudentListsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All students will adhere to the rules of Jami&apos;ah.
        /// All students of Jama&apos;a&apos;ah will perform Salat in Jama-&apos;at.
        /// If there is evidence to take intoxicant or unlawful food, then he will be expelled from Jami&apos;ah.
        /// No one can participate in any type of program without the responsibility of the responsible person.
        /// No student can be involved in political parties or any other organization. If proven, the authorities will take action according to the law.
        /// No student can go to the market without much need. From  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StudentRegulation {
            get {
                return ResourceManager.GetString("StudentRegulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Code of Conduct.
        /// </summary>
        public static string StudentRegulationHeading {
            get {
                return ResourceManager.GetString("StudentRegulationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your room, bed, clothes and clothes clean and tidy.
        /// Without permission, they will not be in each other&apos;s room.
        /// Do not disturb another student during reading, sleep, eating etc.
        /// After 11pm the room lights will be closed.
        /// If there is any problem, the hostel will inform the super / class teacher.
        /// No student will be able to use or hold mobile phone in Jami&apos;ah. Otherwise necessary action will be taken.
        /// With permission from the salam, the office and the teacher will enter the hall.
        /// At the appoi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StudentResidentialConvention {
            get {
                return ResourceManager.GetString("StudentResidentialConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Residential Conventions.
        /// </summary>
        public static string StudentResidentialConventionHeading {
            get {
                return ResourceManager.GetString("StudentResidentialConventionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Syllabus {
            get {
                return ResourceManager.GetString("Syllabus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SyllabusHeading {
            get {
                return ResourceManager.GetString("SyllabusHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be a committee with al-Jami&apos;ah as-Salafiyah students. The responsible teachers will be in charge. Where students will be promoting talent development programs. For example, publication of newspapers and magazines, newspapers and so on.
        ///Note that there will be two branches under &apos;Abana&apos;.
        ///Composed of students studying in a Jami&apos;ah.
        ///The other is made up of students coming out of Jami&apos;ah. Who are employed at their own work place in different parts of the country..
        /// </summary>
        public static string TeacherStudentComitte {
            get {
                return ResourceManager.GetString("TeacherStudentComitte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher-student committee.
        /// </summary>
        public static string TeacherStudentComitteHeading {
            get {
                return ResourceManager.GetString("TeacherStudentComitteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaikh Muzaffar is Hadith Teacher, Al-Marqazul islami as-Salafi, and Member of Darul iftaa, Rajshahi. also SPEAKER at PEACE TV BANGLA [page run by student]
        ///
        ///Early life and Education:
        ///Shaikh Muzaffar was born on 01.01.1985 in a respectablel family in the village Bawsha hedhatipara in the BAGHAA Thana of the RAJSHAHI District, Bangladesh. He passed the Dakhil (2000), Alim (2003) and Fazil (2007) public examinations from Madrasha Education Board. In 2008 he passed the Dawra Hadith from Aladipur Salafia Madr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VicePrincipal {
            get {
                return ResourceManager.GetString("VicePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice Principal.
        /// </summary>
        public static string VicePrincipalHeading {
            get {
                return ResourceManager.GetString("VicePrincipalHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students will be given personal amendment ceremony after 4th grade every Thursday. There will be an opportunity to give lectures on Bangla, English, Arabic at least twice a month on each subject and accordingly according to this &apos;Islahul Baiyan&apos; will be formed. Which is mandatory for all students. The subject matter of each language will be determined.
        ///&apos;Islaahul Baiyan&apos; will be arranged &apos;Abanaye Jami&apos;ah as-Salafiyah&apos; and there will be certain teachers in the review..
        /// </summary>
        public static string WeeklyPersonalTraining {
            get {
                return ResourceManager.GetString("WeeklyPersonalTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly speeches training.
        /// </summary>
        public static string WeeklyPersonalTrainingHeading {
            get {
                return ResourceManager.GetString("WeeklyPersonalTrainingHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assalamu Alaikum. (May Peace be upon you). All praise is due to Almighty Allah Ta-Ala. May Darud and Salaam be poured upon our latest and greatest Rasul Muhammad (Sm.) You are cordially welcome to our official website of Al Jamiah As Salafiah.
        ///Al Jamiah As Salafia is a modern and standard Islamic institution founded and directed by Shaykh Abdur Razzak Bin Yusuf Hafizahullah, one of the greatest Islamic scholars of the country, an active worker of Quran and Hadeeth, dear personality of pious brothers and th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeDetails {
            get {
                return ResourceManager.GetString("WelcomeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message.
        /// </summary>
        public static string WelcomeHeading {
            get {
                return ResourceManager.GetString("WelcomeHeading", resourceCulture);
            }
        }
    }
}
