//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBootstrapSite1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppBootstrapSite1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission.
        /// </summary>
        public static string AdmissionHeading {
            get {
                return ResourceManager.GetString("AdmissionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdmissionSubtitle {
            get {
                return ResourceManager.GetString("AdmissionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GalleryDetails {
            get {
                return ResourceManager.GetString("GalleryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string GalleryHeading {
            get {
                return ResourceManager.GetString("GalleryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying in the light of its own syllabus determined in the form of advanced syllabus of local and foreign institutions.
        ///Directed by a handful of skilled, experienced, hardworking and dedicated teachers from various universities and universities of the country and abroad.
        ///If you are resident then always supervised by the teachers.
        ///A daily meal of 3 &apos;daily&apos; food as well as vegetarian and vegetarian food.
        ///Along with attaining full proficiency in Arabic and English language, there is also a chance to gain  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JamiyahLifeDetails {
            get {
                return ResourceManager.GetString("JamiyahLifeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madrasa Characteristics.
        /// </summary>
        public static string JamiyahLifeHeading {
            get {
                return ResourceManager.GetString("JamiyahLifeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoticeDetails {
            get {
                return ResourceManager.GetString("NoticeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string NoticeHeading {
            get {
                return ResourceManager.GetString("NoticeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoticeSubtitle {
            get {
                return ResourceManager.GetString("NoticeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OurMadrashaDetails {
            get {
                return ResourceManager.GetString("OurMadrashaDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Madrasha.
        /// </summary>
        public static string OurMadrashaHeading {
            get {
                return ResourceManager.GetString("OurMadrashaHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Shaykh Abdur Razzaq bin Yusuf&apos; &apos;To spread the teachings of Quran and Saheeh hadeeth on the soil of Bangladesh on 24th August 2013, in the Rupganj, Narayanganj, and in February 2016, in Rajshahi,&apos; Al-Jami&apos;ah as-Salafiyah &apos;, two simultaneous standard Islamic  &apos;Shaykh Abdur Razzaq bin Yusuf&apos; &apos;To spread the teachings of Quran and Saheeh hadeeth on the soil of Bangladesh on 24th August 2013, in the Rupganj, Narayanganj, and in February 2016, in Rajshahi,&apos; Al-Jami&apos;ah as-Salafiyah &apos;, two simultaneous standard Isl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OurMadrashaSubtitle {
            get {
                return ResourceManager.GetString("OurMadrashaSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Salamu Alaikum Praise be to Allah alone. Darud and Salam should be distributed to the Prophet (ﷺ). The first commandment of Allah is &quot;read&quot;. Welcome to our official web site.
        ///
        ///Honorable readers!
        ///You are aware that since August 2013, Shaykh Abdur Razzaq bin Yusuf has managed to establish Al-Jami&apos;ah as Salafiyyah for the purpose of preparing algebraic scholars in harmony with the Holy Quran and Chhih Hadeeth as well as modern education.
        ///Within a year of the establishment of Jami&apos;ah Salafiyah, with the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeDetails {
            get {
                return ResourceManager.GetString("WelcomeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message.
        /// </summary>
        public static string WelcomeHeading {
            get {
                return ResourceManager.GetString("WelcomeHeading", resourceCulture);
            }
        }
    }
}
