//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBootstrapSite1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JamiyahDBEntities : DbContext
    {
        public JamiyahDBEntities()
            : base("name=JamiyahDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Forms> Forms { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<StaffList> StaffList { get; set; }
        public virtual DbSet<Usergroup> Usergroup { get; set; }
        public virtual DbSet<UserGroupForm> UserGroupForm { get; set; }
        public virtual DbSet<UserGroupModule> UserGroupModule { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
